eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    hostname: localhost
spring:
  application:
    name: custaccountgateway
  cloud:
    discovery:
      enabled: true



management:
  endpoint:
    web:
      exposure:
        include: "*"

server:
  port: 8060